const generateData = () => {
  var data = [];
  for (let i = 0; i < 200; i++) {
    var firstname = [
      "Adrián",
      "Agustín",
      "Alberto",
      "Alejandro",
      "Alexander",
      "Alexis",
      "Alonso",
      "Andrés Felipe",
      "Ángel",
      "Anthony",
      "Antonio",
      "Bautista",
      "Benicio",
      "Benjamín",
      "Carlos",
      "Carlos Alberto",
      "Carlos Eduardo",
      "Carlos Roberto",
      "César",
      "Cristóbal",
      "Daniel",
      "David",
      "Diego",
      "Dylan",
      "Eduardo",
      "Emiliano",
      "Emmanuel",
      "Enrique",
      "Erik",
      "Ernesto",
      "Ethan",
      "Fabián",
      "Facundo",
      "Felipe",
      "Félix",
      "Félix María",
      "Fernando",
      "Francisco",
      "Francisco Javier",
      "Gabriel",
      "Gaspar",
      "Gustavo Adolfo",
      "Hugo",
      "Ian",
      "Iker",
      "Isaac",
      "Jacob",
      "Javier",
      "Jayden",
      "Jeremy",
      "Jerónimo",
      "Jesús",
      "Jesús Antonio",
      "Jesús Víctor",
      "Joaquín",
      "Jorge",
      "Jorge  Alberto",
      "Jorge Luis",
      "José",
      "José Antonio",
      "José Daniel",
      "José David",
      "José Francisco",
      "José Gregorio",
      "José Luis",
      "José Manuel",
      "José Pablo",
      "Josué",
      "Juan",
      "Juan Ángel",
      "Juan Carlos",
      "Juan David",
      "Juan Esteban",
      "Juan Ignacio",
      "Juan José",
      "Juan Manuel",
      "Juan Pablo",
      "Juan Sebastián",
      "Julio",
      "Julio Cesar",
      "Justin",
      "Kevin",
      "Lautaro",
      "Liam",
      "Lian",
      "Lorenzo",
      "Lucas",
      "Luis",
      "Luis Alberto",
      "Luis Emilio",
      "Luis Fernando",
      "Manuel",
      "Manuel Antonio",
      "Marco Antonio",
      "Mario",
      "Martín",
      "Mateo",
      "Matías",
      "Maximiliano",
      "Maykel",
      "Miguel",
      "Miguel  ngel",
      "Nelson",
      "Noah",
      "Oscar",
      "Pablo",
      "Pedro",
      "Rafael",
      "Ramón",
      "Raúl",
      "Ricardo",
      "Rigoberto",
      "Roberto",
      "Rolando",
      "Samuel",
      "Samuel David",
      "Santiago",
      "Santino",
      "Santos",
      "Sebastián",
      "Thiago",
      "Thiago Benjamín",
      "Tomás",
      "Valentino",
      "Vicente",
      "Víctor",
      "Víctor Hugo",
    ];
    var lastname = [
      "Garcia",
      "Gonzalez",
      "Rodriguez",
      "Fernandez",
      "Lopez",
      "Martinez",
      "Sanchez",
      "Perez",
      "Gomez",
      "Martin",
      "Jimenez",
      "Ruiz",
      "Hernandez",
      "Diaz",
      "Moreno",
      "Alvarez",
      "Muñoz",
      "Romero",
      "Alonso",
      "Gutierrez",
      "Navarro",
      "Torres",
      "Dominguez",
      "Vazquez",
      "Ramos",
      "Gil",
      "Ramirez",
      "Serrano",
      "Blanco",
      "Suarez",
      "Molina",
      "Morales",
      "Ortega",
      "Delgado",
      "Castro",
      "Ortiz",
      "Rubio",
      "Marin",
      "Sanz",
      "Nuñez",
      "Iglesias",
      "Medina",
      "Garrido",
      "Santos",
      "Castillo",
      "Cortes",
      "Lozano",
      "Guerrero",
      "Cano",
      "Prieto",
      "Mendez",
      "Calvo",
      "Cruz",
      "Gallego",
      "Vidal",
      "Leon",
      "Herrera",
      "Marquez",
      "Peña",
      "Cabrera",
      "Flores",
      "Campos",
      "Vega",
      "Diez",
      "Fuentes",
      "Carrasco",
      "Caballero",
      "Nieto",
      "Reyes",
      "Aguilar",
      "Pascual",
      "Herrero",
      "Santana",
      "Lorenzo",
      "Hidalgo",
      "Montero",
      "Ibañez",
      "Gimenez",
      "Ferrer",
      "Duran",
      "Vicente",
      "Benitez",
      "Mora",
      "Santiago",
      "Arias",
      "Vargas",
      "Carmona",
      "Crespo",
      "Roman",
      "Pastor",
      "Soto",
      "Saez",
      "Velasco",
      "Soler",
      "Moya",
      "Esteban",
      "Parra",
      "Bravo",
      "Gallardo",
      "Rojas",
      "Pardo",
      "Merino",
      "Franco",
      "Espinosa",
      "Izquierdo",
      "Lara",
      "Rivas",
      "Silva",
      "Rivera",
      "Casado",
      "Arroyo",
      "Redondo",
      "Camacho",
      "Rey",
      "Vera",
      "Otero",
      "Luque",
      "Galan",
      "Montes",
      "Rios",
      "Sierra",
      "Segura",
      "Carrillo",
      "Marcos",
      "Marti",
      "Soriano",
      "Mendoza",
    ];
    var rand_first = Math.floor(Math.random() * firstname.length);
    var rand_last = Math.floor(Math.random() * lastname.length);
    var numC = Math.floor(Math.random() * 12);
    var cursoN = getCursos()[numC].nombre;
    data.push({
      nombre: firstname[rand_first] + " " + lastname[rand_last],
      edad: Math.floor(Math.random() * 50 + 15),
      curso: cursoN,
    });
  }
  return data;
};

const getPersonas = () => {
  //return generateData();
  return [
    { nombre: "Marco Antonio Parra", edad: 26, curso: "Electiva I" },
    {
      nombre: "Marco Antonio Jimenez",
      edad: 60,
      curso: "Programación avanzada",
    },
    { nombre: "César Calvo", edad: 46, curso: "Int. Artificial" },
    { nombre: "Juan Esteban Crespo", edad: 34, curso: "Programación básica" },
    { nombre: "Jayden Prieto", edad: 24, curso: "Taller de diseño" },
    { nombre: "Carlos Rodriguez", edad: 31, curso: "Electiva I" },
    { nombre: "Juan David Nieto", edad: 51, curso: "Taller de diseño" },
    { nombre: "Ethan Serrano", edad: 17, curso: "Calculo II" },
    { nombre: "Alonso Prieto", edad: 17, curso: "Deporte formativo" },
    { nombre: "Gustavo Adolfo Ibañez", edad: 63, curso: "Electiva I" },
    { nombre: "Ricardo Morales", edad: 38, curso: "Programación avanzada" },
    { nombre: "Santiago Ramos", edad: 37, curso: "Electiva I" },
    { nombre: "Juan José Perez", edad: 38, curso: "Ing. software II" },
    { nombre: "Jayden Moya", edad: 59, curso: "Deporte formativo" },
    { nombre: "José Daniel Torres", edad: 24, curso: "Electiva I" },
    { nombre: "Ernesto Rivera", edad: 47, curso: "Calculo II" },
    { nombre: "Ramón Prieto", edad: 48, curso: "Programación avanzada" },
    { nombre: "Jorge Campos", edad: 49, curso: "Programación avanzada" },
    { nombre: "Jesús Perez", edad: 41, curso: "Electiva I" },
    { nombre: "José Daniel Santiago", edad: 21, curso: "Ing. software II" },
    { nombre: "Carlos Eduardo Sanz", edad: 46, curso: "Taller de diseño" },
    { nombre: "César Medina", edad: 62, curso: "Taller de diseño" },
    {
      nombre: "Jorge Luis Caballero",
      edad: 38,
      curso: "Programación avanzada",
    },
    { nombre: "Lucas Aguilar", edad: 25, curso: "Programación avanzada" },
    { nombre: "Joaquín Ramirez", edad: 34, curso: "Taller de diseño" },
    { nombre: "Samuel David Castro", edad: 27, curso: "Electiva I" },
    { nombre: "Jorge Velasco", edad: 48, curso: "Electiva I" },
    { nombre: "Nelson Perez", edad: 26, curso: "Calculo I" },
    { nombre: "José Gregorio Cano", edad: 45, curso: "Calculo II" },
    { nombre: "Agustín Cruz", edad: 35, curso: "Calculo II" },
    { nombre: "Oscar Vera", edad: 39, curso: "Programación avanzada" },
    { nombre: "José Luis Gallardo", edad: 32, curso: "Programación avanzada" },
    { nombre: "Juan Carlos Gonzalez", edad: 16, curso: "Electiva I" },
    { nombre: "Ethan Vicente", edad: 24, curso: "Deporte formativo" },
    { nombre: "Fernando Molina", edad: 30, curso: "Electiva I" },
    { nombre: "Juan Sebastián Soriano", edad: 39, curso: "Electiva I" },
    { nombre: "Ernesto Hidalgo", edad: 60, curso: "Electiva I" },
    { nombre: "José Segura", edad: 28, curso: "Calculo I" },
    { nombre: "Matías Soriano", edad: 59, curso: "Programación avanzada" },
    { nombre: "Julio Soriano", edad: 55, curso: "Ing. software I" },
    { nombre: "José Gregorio Rivera", edad: 27, curso: "Electiva I" },
    { nombre: "Luis Pardo", edad: 25, curso: "Calculo II" },
    { nombre: "Carlos Garrido", edad: 63, curso: "Programación avanzada" },
    { nombre: "Mario Pardo", edad: 37, curso: "Ing. software II" },
    { nombre: "Ángel Delgado", edad: 42, curso: "Electiva I" },
    { nombre: "Juan Manuel Torres", edad: 45, curso: "Deporte formativo" },
    { nombre: "Juan Manuel Herrero", edad: 24, curso: "Calculo I" },
    { nombre: "Lian Parra", edad: 42, curso: "Programación avanzada" },
    { nombre: "Miguel Camacho", edad: 62, curso: "Calculo I" },
    { nombre: "Antonio Pastor", edad: 46, curso: "Electiva I" },
    { nombre: "Mario Bravo", edad: 15, curso: "Programación avanzada" },
    { nombre: "David Segura", edad: 29, curso: "Ing. software I" },
    { nombre: "Luis Emilio Gomez", edad: 57, curso: "Taller de diseño" },
    { nombre: "Jorge  Alberto Morales", edad: 22, curso: "Ing. software I" },
    { nombre: "Facundo Prieto", edad: 52, curso: "Ing. software I" },
    { nombre: "Santiago Marti", edad: 29, curso: "Programación básica" },
    { nombre: "Manuel Castillo", edad: 39, curso: "Programación avanzada" },
    { nombre: "Alberto Ortiz", edad: 16, curso: "Ing. software I" },
    { nombre: "Matías Mendoza", edad: 26, curso: "Programación avanzada" },
    { nombre: "Felipe Nieto", edad: 17, curso: "Taller de diseño" },
    { nombre: "Ernesto Gimenez", edad: 28, curso: "Ing. software II" },
    { nombre: "Daniel Navarro", edad: 20, curso: "Programación avanzada" },
    { nombre: "Juan Lozano", edad: 24, curso: "Calculo II" },
    { nombre: "Jesús Víctor Camacho", edad: 20, curso: "Int. Artificial" },
    { nombre: "Rolando Duran", edad: 38, curso: "Electiva I" },
    { nombre: "Mario Lorenzo", edad: 57, curso: "Taller de diseño" },
    { nombre: "Juan Carlos Garrido", edad: 33, curso: "Int. Artificial" },
    {
      nombre: "Carlos Roberto Medina",
      edad: 46,
      curso: "Programación avanzada",
    },
    { nombre: "Juan Ignacio Pardo", edad: 19, curso: "Electiva I" },
    { nombre: "Gustavo Adolfo Bravo", edad: 38, curso: "Ing. software I" },
    { nombre: "Lian Alvarez", edad: 42, curso: "Programación avanzada" },
    { nombre: "Jayden Montero", edad: 46, curso: "Programación básica" },
    { nombre: "Marco Antonio Sanz", edad: 25, curso: "Electiva I" },
    { nombre: "Agustín Montero", edad: 40, curso: "Taller de diseño" },
    { nombre: "Lorenzo Alonso", edad: 25, curso: "Calculo II" },
    { nombre: "Francisco Rey", edad: 27, curso: "Ing. software I" },
    { nombre: "Maximiliano Mora", edad: 53, curso: "Programación avanzada" },
    { nombre: "Félix María Diez", edad: 45, curso: "Programación avanzada" },
    { nombre: "Javier Suarez", edad: 61, curso: "Taller de diseño" },
    { nombre: "Manuel Parra", edad: 47, curso: "Programación avanzada" },
    { nombre: "Benjamín Rios", edad: 62, curso: "Deporte formativo" },
    { nombre: "Thiago Romero", edad: 60, curso: "Calculo II" },
    { nombre: "Eduardo Lopez", edad: 57, curso: "Electiva I" },
    { nombre: "Jeremy Santiago", edad: 57, curso: "Programación avanzada" },
    { nombre: "Juan Manuel Otero", edad: 20, curso: "Electiva I" },
    { nombre: "Ernesto Lopez", edad: 17, curso: "Electiva I" },
    { nombre: "Ángel Navarro", edad: 58, curso: "Int. Artificial" },
    { nombre: "Julio Cesar Ferrer", edad: 24, curso: "Electiva I" },
    { nombre: "Bautista Franco", edad: 32, curso: "Programación básica" },
    { nombre: "Eduardo Alonso", edad: 20, curso: "Programación avanzada" },
    { nombre: "Jorge Carmona", edad: 19, curso: "Deporte formativo" },
    { nombre: "Félix María Gil", edad: 50, curso: "Int. Artificial" },
    { nombre: "Luis Alberto Espinosa", edad: 54, curso: "Electiva I" },
    { nombre: "Andrés Felipe Diez", edad: 15, curso: "Int. Artificial" },
    { nombre: "Ian Blanco", edad: 48, curso: "Taller de diseño" },
    { nombre: "Miguel  ngel Ortiz", edad: 64, curso: "Ing. software II" },
    { nombre: "Daniel Gallego", edad: 32, curso: "Taller de diseño" },
    { nombre: "Alonso Diaz", edad: 15, curso: "Ing. software I" },
    { nombre: "Gaspar Ortiz", edad: 62, curso: "Electiva I" },
    { nombre: "Gaspar Alonso", edad: 63, curso: "Deporte formativo" },
    { nombre: "Thiago Cruz", edad: 32, curso: "Ing. software I" },
    { nombre: "Anthony Vera", edad: 52, curso: "Programación avanzada" },
    { nombre: "José Gregorio Pascual", edad: 60, curso: "Int. Artificial" },
    { nombre: "José David Hidalgo", edad: 38, curso: "Calculo I" },
    { nombre: "Fabián Alvarez", edad: 63, curso: "Electiva I" },
    { nombre: "Jerónimo Carrillo", edad: 43, curso: "Taller de diseño" },
    { nombre: "Oscar Blanco", edad: 26, curso: "Programación avanzada" },
    { nombre: "Víctor Hugo Soriano", edad: 34, curso: "Deporte formativo" },
    { nombre: "José Antonio Moya", edad: 33, curso: "Ing. software II" },
    { nombre: "Rafael Medina", edad: 31, curso: "Electiva I" },
    { nombre: "Noah Hidalgo", edad: 36, curso: "Electiva I" },
    { nombre: "Andrés Felipe Martin", edad: 64, curso: "Int. Artificial" },
    { nombre: "César Medina", edad: 59, curso: "Deporte formativo" },
    { nombre: "Benicio Muñoz", edad: 32, curso: "Programación avanzada" },
    { nombre: "Ricardo Alvarez", edad: 22, curso: "Calculo I" },
    { nombre: "Miguel Campos", edad: 25, curso: "Calculo II" },
    { nombre: "Manuel Lozano", edad: 62, curso: "Electiva I" },
    { nombre: "Justin Dominguez", edad: 52, curso: "Taller de diseño" },
    { nombre: "Francisco Javier Moya", edad: 41, curso: "Electiva I" },
    { nombre: "Daniel Diez", edad: 57, curso: "Programación avanzada" },
    { nombre: "Enrique Perez", edad: 18, curso: "Calculo II" },
    { nombre: "Carlos Eduardo Castro", edad: 23, curso: "Deporte formativo" },
    { nombre: "Jesús Gonzalez", edad: 46, curso: "Electiva I" },
    { nombre: "Juan Pablo Dominguez", edad: 23, curso: "Ing. software I" },
    { nombre: "Hugo Reyes", edad: 43, curso: "Programación avanzada" },
    { nombre: "Samuel Parra", edad: 47, curso: "Calculo I" },
    { nombre: "Adrián Gil", edad: 62, curso: "Deporte formativo" },
    { nombre: "Jorge Carrasco", edad: 64, curso: "Electiva I" },
    { nombre: "Dylan Franco", edad: 48, curso: "Programación básica" },
    { nombre: "José Rey", edad: 36, curso: "Electiva I" },
    { nombre: "Fabián Calvo", edad: 52, curso: "Programación básica" },
    { nombre: "Diego Marti", edad: 29, curso: "Programación avanzada" },
    { nombre: "Carlos Vidal", edad: 61, curso: "Int. Artificial" },
    { nombre: "Félix María Peña", edad: 28, curso: "Deporte formativo" },
    { nombre: "Felipe Duran", edad: 63, curso: "Calculo II" },
    { nombre: "Tomás Diaz", edad: 20, curso: "Taller de diseño" },
    { nombre: "Tomás Sierra", edad: 49, curso: "Programación avanzada" },
    { nombre: "Anthony Silva", edad: 26, curso: "Ing. software I" },
    { nombre: "Carlos Suarez", edad: 60, curso: "Programación básica" },
    { nombre: "Anthony Bravo", edad: 21, curso: "Calculo I" },
    { nombre: "Liam Pardo", edad: 25, curso: "Ing. software II" },
    { nombre: "Jorge  Alberto Gomez", edad: 19, curso: "Electiva I" },
    { nombre: "Hugo Blanco", edad: 57, curso: "Calculo I" },
    { nombre: "Juan Pablo Pastor", edad: 24, curso: "Programación avanzada" },
    { nombre: "Félix María Cano", edad: 24, curso: "Ing. software II" },
    {
      nombre: "Francisco Javier Lorenzo",
      edad: 20,
      curso: "Deporte formativo",
    },
    { nombre: "Martín Martinez", edad: 47, curso: "Calculo II" },
    { nombre: "Víctor Hugo Hidalgo", edad: 26, curso: "Int. Artificial" },
    { nombre: "Antonio Redondo", edad: 64, curso: "Int. Artificial" },
    { nombre: "Joaquín Luque", edad: 22, curso: "Programación básica" },
    { nombre: "Lucas Rubio", edad: 63, curso: "Programación avanzada" },
    { nombre: "Fabián Redondo", edad: 57, curso: "Int. Artificial" },
    { nombre: "Miguel Soriano", edad: 59, curso: "Taller de diseño" },
    { nombre: "Marco Antonio Lozano", edad: 43, curso: "Calculo I" },
    { nombre: "Santino Vera", edad: 29, curso: "Deporte formativo" },
    { nombre: "Luis Alberto Vera", edad: 29, curso: "Calculo II" },
    { nombre: "Santiago Aguilar", edad: 38, curso: "Calculo I" },
    { nombre: "Jesús Santana", edad: 45, curso: "Programación avanzada" },
    { nombre: "José Manuel Arroyo", edad: 47, curso: "Programación avanzada" },
    { nombre: "Vicente Merino", edad: 64, curso: "Programación avanzada" },
    { nombre: "Alonso Casado", edad: 31, curso: "Deporte formativo" },
    { nombre: "Samuel David Cruz", edad: 25, curso: "Int. Artificial" },
    { nombre: "Jerónimo Galan", edad: 15, curso: "Programación avanzada" },
    { nombre: "Facundo Calvo", edad: 19, curso: "Int. Artificial" },
    { nombre: "Francisco Javier Mendez", edad: 55, curso: "Electiva I" },
    { nombre: "Maykel Rios", edad: 21, curso: "Int. Artificial" },
    { nombre: "Rolando Gallardo", edad: 15, curso: "Taller de diseño" },
    { nombre: "Juan Esteban Ferrer", edad: 58, curso: "Electiva I" },
    { nombre: "Daniel Moreno", edad: 33, curso: "Int. Artificial" },
    { nombre: "Gabriel Medina", edad: 63, curso: "Taller de diseño" },
    { nombre: "Martín Suarez", edad: 30, curso: "Ing. software II" },
    { nombre: "Alonso Soriano", edad: 50, curso: "Programación avanzada" },
    { nombre: "Valentino Mendoza", edad: 24, curso: "Taller de diseño" },
    { nombre: "Félix Herrero", edad: 37, curso: "Programación avanzada" },
    { nombre: "Alejandro Ferrer", edad: 16, curso: "Taller de diseño" },
    { nombre: "Francisco Mora", edad: 36, curso: "Ing. software I" },
    { nombre: "Lautaro Gil", edad: 59, curso: "Programación avanzada" },
    { nombre: "Alejandro Marin", edad: 56, curso: "Ing. software I" },
    { nombre: "Santos Montes", edad: 37, curso: "Programación avanzada" },
    { nombre: "Roberto Garcia", edad: 47, curso: "Ing. software II" },
    { nombre: "Daniel Ortiz", edad: 40, curso: "Programación avanzada" },
    { nombre: "Félix Campos", edad: 29, curso: "Programación básica" },
    { nombre: "José Antonio Flores", edad: 15, curso: "Programación básica" },
    { nombre: "Felipe Reyes", edad: 43, curso: "Int. Artificial" },
    { nombre: "Liam Romero", edad: 53, curso: "Programación avanzada" },
    { nombre: "Jorge  Alberto Gallardo", edad: 19, curso: "Calculo II" },
    { nombre: "Ricardo Espinosa", edad: 52, curso: "Electiva I" },
    { nombre: "César Rodriguez", edad: 33, curso: "Programación avanzada" },
    { nombre: "Ethan Marquez", edad: 55, curso: "Electiva I" },
    { nombre: "Rigoberto Vazquez", edad: 63, curso: "Calculo II" },
    { nombre: "Lucas Redondo", edad: 28, curso: "Programación avanzada" },
    { nombre: "Ian Perez", edad: 28, curso: "Ing. software I" },
    { nombre: "Manuel Antonio Cabrera", edad: 33, curso: "Calculo II" },
    { nombre: "César Galan", edad: 46, curso: "Taller de diseño" },
    { nombre: "Cristóbal Otero", edad: 49, curso: "Ing. software II" },
    { nombre: "Facundo Prieto", edad: 22, curso: "Ing. software I" },
    { nombre: "Luis Fernando Casado", edad: 41, curso: "Ing. software I" },
    { nombre: "Diego Gutierrez", edad: 27, curso: "Electiva I" },
    { nombre: "Andrés Felipe Carrasco", edad: 53, curso: "Deporte formativo" },
    { nombre: "Hugo Ramos", edad: 60, curso: "Ing. software II" },
  ];
};

const getCursos = () => {
  return [
    {
      cod: "c0001",
      nombre: "Programación avanzada",
    },
    {
      cod: "c0002",
      nombre: "Programación básica",
    },
    {
      cod: "c0003",
      nombre: "Programación avanzada",
    },
    {
      cod: "c0004",
      nombre: "Taller de diseño",
    },
    {
      cod: "c0005",
      nombre: "Calculo I",
    },
    {
      cod: "c0006",
      nombre: "Calculo II",
    },
    {
      cod: "c0007",
      nombre: "Ing. software I",
    },
    {
      cod: "c0008",
      nombre: "Ing. software II",
    },
    {
      cod: "c0009",
      nombre: "Deporte formativo",
    },

    {
      cod: "c0010",
      nombre: "Electiva I",
    },

    {
      cod: "c0011",
      nombre: "Electiva I",
    },

    {
      cod: "c0012",
      nombre: "Int. Artificial",
    },
  ];
};

module.exports = {
  getPersonas,
  getCursos,
};
